name: emogotchi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  colorful_safe_area: ^1.0.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  table_calendar: ^3.1.3
  fl_chart: ^0.65.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  typewritertext: ^3.0.9
  permission_handler: ^11.3.0
  confetti: ^0.8.0
  flutter_native_splash: ^2.4.4
  flutter_email_sender: ^7.0.0
  flutter_feather_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

  path_provider: ^2.1.2
  provider:
  http:
  device_info_plus: ^11.2.0
  flutter_chat_bubble: ^2.0.2
  

flutter_native_splash:
  color: "#B1E0F0"
  color_dark: "#B1E0F0"
  
  image: assets/icon.png
  image_dark: assets/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/dog/
    - assets/hamster/
    - assets/penguin/
    - assets/pig/
    - assets/penguin_egg/
    - assets/hamster_egg/
    - assets/dog_egg/
    - assets/pig_egg/
    - assets/tiger_egg/


    - assets/tiger/
    - assets/emoji/
    - assets/doctor.png
    - assets/homepage/
    - shorebird.yaml 

